    <?php
    include "../part/head.php"
    ?>


<h1 class="con  ">Main</h1>
<div>
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde porro, voluptas consequuntur, enim soluta obcaecati voluptatem veniam incidunt aperiam omnis rem, similique ut odio nulla illum dolores perferendis aliquid fugit.
    Facere, enim aspernatur. Voluptas optio, impedit quidem est distinctio exercitationem iure libero asperiores? Rerum saepe vitae dolorum cupiditate, voluptates repellat voluptatibus! Assumenda fugit omnis tenetur aliquam quibusdam repellat necessitatibus reprehenderit!
    Odio delectus minus maiores rerum alias iure dolorem nemo inventore expedita, vitae corrupti nam facere quae error recusandae ullam reprehenderit quibusdam autem quaerat quis. Architecto accusamus voluptas inventore quas deserunt.
    Hic, quos. Rerum, accusantium, aut tempore animi impedit aliquid error corrupti incidunt itaque eaque quam consequuntur porro dolor quidem sunt maxime qui, eum tenetur quia cum fugiat vero aspernatur provident?
    Natus suscipit repellendus, dolorum totam dignissimos ad deserunt saepe minima corrupti fugit laudantium, in architecto maxime. Error aliquam consectetur inventore dicta modi velit, odio exercitationem impedit magnam excepturi voluptate ex?
    Suscipit quia iure perspiciatis, aliquid doloribus modi corporis eaque architecto tempora, quibusdam culpa, aut neque dolor porro voluptatum est rerum iusto impedit. Ratione dignissimos minus maiores, rerum ullam totam. Architecto.
    Facilis ratione error qui maxime! Aut iusto ipsam voluptate? Nam id perspiciatis sed soluta, laboriosam quas ut, ab at nulla voluptatum corporis modi totam debitis non illum aut commodi numquam!
    Molestias odit repellat laudantium doloribus autem totam corrupti eius quidem, esse dolore beatae consectetur dolores ab dolor error repudiandae adipisci amet voluptates officiis debitis veritatis? Omnis incidunt blanditiis adipisci ipsa!
    Vitae natus sint saepe obcaecati illum quis vel eligendi, cumque assumenda nihil repellendus? Asperiores porro, sint cum nemo ducimus minus sit, quibusdam quisquam excepturi, optio libero modi dolore odit deserunt.
    Accusamus amet dolores repudiandae obcaecati doloribus quis ullam eum soluta, culpa magnam modi repellendus impedit id. Odit perferendis ea dolores aliquam laborum repellat numquam architecto, vel corrupti doloremque commodi rem?
    Corporis itaque culpa excepturi nulla velit, laboriosam cupiditate explicabo architecto, ducimus voluptatibus voluptatem est aperiam cumque quia consequatur numquam id harum, ratione laborum! Ea vitae quibusdam commodi nobis temporibus nisi?
    Consectetur quidem vero nemo quos accusamus id doloremque laudantium quibusdam, repudiandae nostrum dignissimos? Vel qui reprehenderit asperiores, laborum praesentium nostrum minima quo architecto aliquid explicabo, amet blanditiis nisi harum rem?
    Deserunt, magnam veritatis. Quos modi eos, nisi provident tempora accusamus. Esse ipsa quisquam repellat ad consequatur commodi? Modi nihil odit debitis accusantium, ut explicabo quae inventore. Recusandae error temporibus accusantium.
    Molestias, architecto iusto exercitationem tempore autem libero. Temporibus rerum perspiciatis recusandae, numquam blanditiis quidem accusantium quaerat quisquam ut quibusdam? Tenetur placeat at, porro perspiciatis inventore reiciendis voluptatum. Molestiae, et illo?
    Eum deserunt delectus suscipit culpa commodi sed dignissimos nemo assumenda minima mollitia quibusdam quisquam, maiores rerum totam consequuntur quaerat illo facere adipisci beatae. Beatae veniam eveniet, quas vero labore temporibus?
    A dicta ratione corporis adipisci consectetur dolorem recusandae deserunt aspernatur porro accusamus neque iusto eligendi architecto iure, illo ad est inventore commodi saepe explicabo provident odit necessitatibus suscipit repudiandae. Repellendus.
    Temporibus dignissimos accusamus, totam quaerat iure obcaecati reiciendis repellendus earum commodi fugiat impedit deleniti explicabo, provident natus, facilis voluptatum ea eaque vitae delectus quo quasi magni dicta nulla doloremque. Suscipit.
    Sint magni corrupti praesentium, nam vero cupiditate placeat molestias labore minima qui aliquid, perspiciatis fugiat quis fugit temporibus nisi ea aliquam voluptatum similique, rerum quod ipsum officiis eligendi eius! Obcaecati?
    Consequuntur exercitationem dolorum, ducimus laudantium earum sunt, ex sapiente soluta harum iste quas at culpa rem reiciendis, provident quam in quod doloremque ratione. Animi molestias voluptas nobis sint, et consectetur.
    Repudiandae tempore consectetur mollitia perspiciatis ipsum maiores saepe, corporis molestias officia nobis, temporibus aliquam reiciendis excepturi hic nisi ab quas obcaecati fugit alias beatae ad, tempora dignissimos ipsam numquam. Laborum?
    Facere error, dolores sint vitae illo vero nihil deserunt voluptatem incidunt pariatur adipisci soluta voluptates velit animi iure accusantium libero nulla eligendi et nesciunt impedit quis non. Dicta, quos ea.
    Quaerat, expedita! Dolorum animi recusandae voluptatum porro, optio voluptatem laborum voluptates. Culpa eos minus cupiditate et maiores deserunt harum sit voluptatibus architecto libero at dolor non facilis quam, aspernatur veniam.
    Excepturi totam voluptas impedit suscipit illo sequi quaerat, unde corrupti iure aut esse! Ipsam est mollitia aperiam eaque ipsa officiis aspernatur in inventore repudiandae, quos dolorum, numquam necessitatibus impedit similique.
    Consequuntur fuga possimus, optio quo eligendi accusantium assumenda a odio cumque. Quibusdam reiciendis nisi ratione neque! Dolor animi quisquam consectetur, repellat explicabo sunt voluptatum earum cupiditate eaque quia error quidem.
    Asperiores rerum dolorum id ipsum, molestiae vel harum cum delectus nihil quisquam. Quas doloribus fugit provident tempora ipsa doloremque explicabo, consectetur dolorum maxime error maiores ab omnis. Odio, repellat explicabo.
    Rem commodi, facere necessitatibus cupiditate ab voluptatum at magnam dolor vero fugit possimus fugiat praesentium accusamus deserunt saepe maxime itaque dicta? Repellat quisquam alias laboriosam quae perferendis tenetur architecto harum?
    Labore qui vel, excepturi nostrum provident neque quam, optio facere rerum delectus animi ipsam vitae ut laboriosam similique minima modi sit eos sint quis sapiente voluptatibus. Commodi ea officia possimus.
    Asperiores corrupti adipisci minima vel at molestias accusantium ipsa cumque dolores reprehenderit natus, officia accusamus id. Laboriosam earum doloremque qui accusantium amet eligendi quasi. Est reprehenderit provident recusandae veniam odio.
    Totam neque dicta incidunt deserunt eveniet eligendi quas doloremque quis nam architecto? Nostrum qui accusamus unde, eaque autem aliquam iusto aspernatur fugit? Fuga maxime praesentium reiciendis blanditiis unde provident ipsum.
    Sapiente commodi, fugit ratione sit eius itaque libero. Placeat dolor nam nesciunt a laborum quae tempora aliquid quidem ipsam praesentium reiciendis, esse molestias quisquam est rem eius molestiae fuga corrupti.
    Ex modi facere nesciunt aperiam hic harum consequatur debitis unde perspiciatis dolores distinctio iste ea quo non explicabo incidunt, voluptatem vel placeat, nobis neque sequi dolorum perferendis rerum totam! Voluptates!
    Aliquid consequatur expedita impedit maxime ipsum sapiente debitis! Non amet deserunt impedit fugiat? Quas adipisci quis blanditiis cum cumque vitae accusamus molestias ad reiciendis eos, quos dicta accusantium repellat molestiae!
    Repellat quae nisi soluta aut, laudantium quam alias facilis porro a ad vero vel sit est labore ut quos exercitationem suscipit veniam amet consequuntur. Cumque doloribus molestiae delectus non quas?
    Modi voluptate, vero placeat architecto quae repellat nesciunt suscipit eum doloremque praesentium et dolorem, quam quo cumque consequuntur totam molestias numquam? Maiores eum ea dolorem modi doloremque repellendus cumque quo!
    Alias nisi reiciendis corrupti repellendus excepturi natus cum, aliquam ea eligendi, reprehenderit ullam aspernatur eum doloribus ad iusto velit. Facilis ipsum cupiditate animi iure porro deleniti molestias fugiat dolores eius!
    Rem magni soluta nesciunt totam molestias cum? Placeat, modi quisquam obcaecati veritatis beatae quasi repudiandae quis sunt excepturi molestias dolores quas libero odit voluptate ratione, dicta atque eius est molestiae.
    Fuga nisi incidunt nulla? Consequuntur eveniet, minus quam enim facilis, repellat rem voluptatibus cum ipsam numquam voluptates molestias repudiandae debitis, accusantium autem pariatur maxime eum repellendus error unde. Ipsum, enim.
    Iusto alias ducimus animi debitis? Exercitationem accusantium incidunt inventore laudantium perferendis minima nesciunt blanditiis ab recusandae. Quam fugiat, culpa perferendis molestiae reiciendis quaerat eum nisi consequuntur sapiente eos eveniet illo?
    Et repudiandae corporis quisquam nam amet ratione quam culpa, animi vero provident id dicta similique tenetur fugit consectetur vitae odit odio labore autem a laborum accusamus delectus magni! Amet, fuga?
    Pariatur esse, fugiat sunt, nesciunt tenetur ducimus aliquid quod nam necessitatibus, error molestiae a perspiciatis neque doloribus totam voluptatibus. Nulla eos quaerat fugiat eius? Dolores eius magnam facilis ut tempore?
    Cupiditate autem perspiciatis debitis voluptate numquam amet iusto sunt nesciunt placeat, ullam rem ut nobis minima dolor odio. Aut consequatur repellendus beatae incidunt at commodi saepe labore reprehenderit dolores dicta.
    Libero, distinctio iste vel eaque quae harum illo quam doloremque, nemo deleniti exercitationem ipsa obcaecati beatae recusandae ipsum. Veritatis dignissimos voluptatem ipsa tempore saepe quae, eos reiciendis necessitatibus! Autem, deserunt.
    Sint, recusandae ab perspiciatis a laudantium numquam perferendis praesentium officia rerum quia fugiat placeat quis aut et, unde dicta quas iste optio delectus vel, ex repudiandae quidem esse dolorem! Eos.
    Voluptas voluptatibus labore natus, quas porro officiis deleniti a odio dicta temporibus repellendus tempora error maiores eveniet perspiciatis rerum tempore vero ad, aliquid cum. Dolorem molestiae sed soluta nesciunt at!
    Vitae eius dolor labore minus praesentium sequi sit cumque ea expedita maxime illo aliquid doloribus ipsam, quas, corporis corrupti mollitia pariatur laboriosam iusto qui laudantium dignissimos minima fugiat adipisci. Eveniet.
    Expedita quasi corrupti, dicta vel officiis consequatur natus distinctio explicabo animi nemo culpa rem quos reiciendis error beatae eius aperiam aliquid eum ea corporis asperiores commodi. Deserunt cumque exercitationem voluptates!
    Provident error nemo perferendis aliquid sunt velit repudiandae est laboriosam dolores quae alias excepturi quis sed, nisi cumque fuga suscipit quod illum soluta neque. Maxime fugiat quidem repellat quisquam! Dicta.
    Reprehenderit, ullam at ipsa cumque nam accusantium sit, expedita reiciendis eos nobis maxime, quo id doloremque eveniet repellat iure quas quis sequi nostrum incidunt iusto. Vel ab dolorum perferendis quasi.
    Aspernatur consectetur, unde voluptatibus dolor nam enim perferendis expedita odio cupiditate harum veritatis quam ducimus? Ducimus tempora vel totam cum laborum, corporis provident nemo exercitationem atque? Dolor corporis eligendi perferendis!
    Cupiditate ducimus placeat sapiente voluptatem sed blanditiis quos autem iure expedita doloribus error, quae accusantium sunt odio suscipit assumenda iste et, corrupti nulla molestiae adipisci doloremque veritatis at numquam? Error.
    Laboriosam, error. Possimus assumenda voluptatum nemo dignissimos fuga quas eligendi ad vel molestias ea, sed soluta error nisi quisquam quae, deserunt quod illo ducimus repellat eos adipisci, iste numquam. Maxime?
    Labore illum, explicabo voluptate quisquam delectus quas provident blanditiis maiores dicta sequi. Veritatis modi reiciendis eligendi reprehenderit repellendus illum consequuntur voluptate rem officia, molestias cumque perspiciatis officiis enim dolor earum.
    Excepturi beatae voluptate blanditiis doloremque, ad incidunt dolorum. Ad odit consequatur neque dolorem repellendus cupiditate nobis necessitatibus ullam enim perspiciatis minus laudantium aspernatur, natus sint voluptatem libero, harum vero earum.
    Tempore consectetur tempora, laudantium error sed facere! Nisi numquam vel accusantium voluptatem nesciunt ratione esse repellendus iste cupiditate minus tempore saepe quia ullam, perferendis recusandae maxime praesentium architecto nulla? Autem!
    Molestias deleniti odit aspernatur neque natus pariatur provident enim dolores ipsum unde assumenda architecto aut facilis cumque fugit praesentium ratione, repellat aliquam hic accusantium aliquid eaque? Maxime perferendis repellendus eum.
    Quo, earum aspernatur. Hic deserunt nam delectus labore illum officiis rem a? Architecto explicabo obcaecati dolore eaque, sequi rem. Itaque, porro fugiat ipsa iste odit voluptatibus sit! Earum, modi odit?
    Nesciunt atque exercitationem deserunt necessitatibus est pariatur quia asperiores ex delectus quam. Id odit molestiae, ad repellendus accusamus dolore minima velit cum quibusdam quo maxime repellat! Expedita omnis magni pariatur.
    Dolorem, odio voluptatibus quasi explicabo molestias dolores! Dolorum odit libero reiciendis, et optio voluptas consectetur corporis, delectus commodi perspiciatis incidunt modi, praesentium doloremque ex quidem rem quasi non ad? Dolores.
    Quisquam eum error voluptas omnis, eos dolore necessitatibus soluta beatae aliquam minus possimus facilis ducimus, nulla suscipit quibusdam voluptatibus ad atque sed, autem porro quas expedita quos sit. Molestias, voluptatem.
    Amet, ea deserunt. Inventore aut adipisci illo. Illum nostrum laboriosam asperiores blanditiis? Iste voluptatum dolorem ullam deleniti, recusandae at libero cumque aperiam temporibus qui sed voluptate laudantium autem excepturi eligendi?
    Repellendus, id! Vitae dignissimos reprehenderit illum velit veritatis quasi commodi praesentium aperiam quos aliquam, atque sint doloremque deserunt illo quaerat neque odit excepturi perspiciatis placeat totam deleniti fugiat. Incidunt, enim.
    Ratione ea minima nostrum architecto molestias corporis voluptas labore perferendis explicabo iste accusantium, aspernatur similique eaque sed et non facere nam quam cum deserunt incidunt! Sed, sunt quidem? Sed, maiores.
    Voluptatem, quibusdam est excepturi modi sed, repudiandae quos, velit tenetur nobis nesciunt porro perspiciatis quo vel repellendus quam animi fugiat? Cupiditate nisi iste asperiores itaque veniam tenetur iure consequatur non?
    Vitae hic amet veritatis temporibus repellendus mollitia deleniti a eaque, aut ipsam repudiandae perspiciatis? Voluptate vel facere quam. A recusandae temporibus quos rem ea! Veniam adipisci officia nemo vero. Totam?
    Molestiae in ipsam commodi earum incidunt praesentium, aliquam officiis pariatur iusto ut tempora? Natus ipsam, incidunt accusantium saepe quam dolorum omnis commodi esse nemo voluptatum harum? Ipsam harum totam iure.
    Consequatur sapiente mollitia sit maiores obcaecati blanditiis eos doloribus! Voluptatibus illo quibusdam laudantium iste eveniet assumenda doloribus odio temporibus earum perferendis rem mollitia laborum, fuga ratione repellat fugit molestias magnam.
    Odio quis quam, soluta reprehenderit ducimus itaque dolore, quod sed, perspiciatis at minima iure odit doloribus ab vero? Quo assumenda quidem, odio totam veniam eaque maxime nam atque repudiandae accusamus.
    Soluta porro ut veritatis nemo ipsa deserunt qui excepturi recusandae fugit voluptatum expedita maxime, sint molestiae explicabo praesentium, est reiciendis voluptate at perspiciatis sed? Earum aut tempore eum doloribus explicabo.
    Aspernatur dolorem voluptatum ut facere consectetur sint sapiente veniam quas placeat explicabo quia amet alias ea libero eos repellendus dolore sequi eius doloribus officiis, officia aperiam? Quibusdam ipsa et eum!
    Sed, sunt, placeat labore recusandae aut quod repellat nemo, repudiandae a similique reprehenderit tenetur asperiores temporibus ratione? Laboriosam doloribus ea totam voluptatem reiciendis esse veritatis, voluptate porro quos quam inventore!
    Dolorem ratione id maiores error, veritatis in facere voluptatum rem velit ea explicabo dicta tenetur possimus nobis quas iste quam harum reprehenderit ipsam cupiditate eveniet quasi commodi laboriosam veniam. Ea.
    Architecto magnam doloribus unde tempora facere aperiam rerum fuga magni quos veritatis iste quis, exercitationem, quam voluptatibus aut quibusdam repudiandae, ipsa ut officiis. Maxime, soluta! Dolorum sed reprehenderit quo repellendus.
    Voluptate architecto atque quo voluptas nesciunt. Pariatur laborum excepturi, provident repellendus perferendis cupiditate cum unde tempora. Eos, eveniet vitae corporis doloremque, unde et sapiente doloribus consequatur veniam itaque odio hic.
    Voluptas, suscipit officia saepe esse commodi dicta distinctio similique in enim sint ad perferendis eius fugiat cumque iusto nobis illo explicabo sapiente natus a nesciunt repellat molestias nam. Nesciunt, ex.
    Fuga sequi ipsum vitae sunt iusto quibusdam? Nisi necessitatibus, dolores ratione, velit minus, ex voluptate quam nemo deserunt quaerat iure corporis! Harum saepe similique et? Repellendus, nam hic? Velit, cupiditate.
    Molestias cupiditate excepturi aspernatur modi, repellat itaque quas mollitia, nesciunt placeat nostrum aperiam unde facilis reiciendis saepe nemo nam reprehenderit facere ipsa nobis optio et repellendus obcaecati fuga. Tenetur, nemo.
    Temporibus atque dolor numquam explicabo delectus ipsam eos ipsa autem, eveniet incidunt voluptatibus pariatur at? Fuga esse repellendus exercitationem quod laboriosam architecto consequuntur recusandae qui iusto quas! Dolor, odit? Blanditiis.
    Nobis totam enim qui, optio ducimus corrupti, facilis quam ea repellat vitae dolores mollitia. Labore, vero. At repellendus, atque quis aut officia ratione inventore, culpa consequuntur quasi voluptatum debitis! Ad.
    Qui aliquid dolorum reiciendis eos enim sed ex fugiat et, obcaecati odio. Itaque voluptatibus, amet, vitae soluta nobis id eius, exercitationem ipsa voluptatum omnis labore dolores veritatis esse hic nostrum!
    Tenetur iste consequuntur neque esse culpa nemo magni porro. Sequi temporibus magnam corporis ipsum dolorum soluta autem quo nemo consequuntur culpa? Cupiditate nobis ut autem perspiciatis animi quaerat expedita quibusdam!
    Ex consequuntur odio molestiae minima sit voluptas adipisci mollitia nam, dolores alias fugit, debitis eligendi, nihil non maiores reprehenderit eaque sapiente quia! Modi officiis ab blanditiis ut, magni alias iste.
    Illum dignissimos autem eaque debitis quod non ullam animi, possimus eligendi magni corrupti illo ab repellendus ipsa tempora at quo reprehenderit ratione commodi enim. Quos quibusdam accusamus iusto sed rerum?
    Reiciendis optio, quis provident expedita sit, dolores, laudantium ab ullam nisi saepe ipsam error repellat nam ex dicta maxime hic iure perferendis voluptas quam. Cumque pariatur magnam mollitia numquam dignissimos.
    Ab sit similique eligendi, neque quo molestiae temporibus, voluptas assumenda nam, aliquid distinctio! Dicta iure quibusdam similique hic officia! Earum ut iure recusandae quisquam officia in sapiente illo doloribus repellat.
    Earum eveniet, consequatur velit expedita praesentium perspiciatis esse eos excepturi est nam sapiente eum accusamus tempore nobis perferendis quos nemo! Sequi aut et id beatae. Hic officiis laboriosam animi facere.
    Fugiat laudantium blanditiis earum odit veniam impedit sit consequatur. Velit ut soluta cupiditate similique impedit ea! Enim provident, alias voluptatum sequi voluptates velit, quas saepe officiis maxime aliquid impedit accusamus!
    Culpa earum magni et quae magnam possimus, minus doloribus vitae maxime sunt fugit, architecto quidem ipsam officiis eveniet? Iure assumenda dolor quod soluta qui, incidunt perferendis quas nostrum ex voluptas?
    Repudiandae, placeat fugit dolorem corporis ipsum dignissimos in fugiat? Sit, iste iure autem distinctio earum consectetur accusantium cum impedit veniam minima officia eligendi omnis ea deleniti dicta exercitationem vel! Eos.
    Aperiam voluptas quam omnis et pariatur incidunt accusamus, minima ea fuga non, voluptatibus quia deserunt consequuntur voluptate architecto labore facilis. Repudiandae, nostrum cumque vero fugit quod quo nisi praesentium voluptatibus.
    Maiores iste debitis laudantium, aliquam molestias magni aliquid facere, exercitationem cumque possimus qui, nulla velit magnam. Praesentium voluptates, delectus dignissimos mollitia, odio neque, sequi quaerat error excepturi unde voluptate totam.
    Modi nam expedita iusto nihil aut et consequatur optio iure aspernatur earum nulla dolor, numquam beatae ex commodi eius, error laudantium harum aperiam quae ducimus reprehenderit sit ipsum! At, voluptatem.
    Accusantium similique beatae, at repellat tempora quod nemo quia quis, iste possimus, quidem voluptate illo. Eos optio omnis id, corrupti iste alias expedita fugit recusandae, aliquid rem voluptate voluptatibus itaque!
    Hic necessitatibus praesentium expedita unde sed libero recusandae dicta officia maxime quisquam totam nostrum cumque ut, odit itaque, enim molestias exercitationem omnis sunt odio accusantium animi iure dignissimos quidem? Sequi.
    Perferendis quam vero quis in, possimus culpa ad non voluptatum iusto iste sit fugiat vel ab tenetur voluptatibus, a repudiandae at unde nisi rem. Ut libero quod iure nobis quaerat?
    Voluptatum hic cupiditate dicta sapiente. Voluptates enim quos ex! Soluta dignissimos sunt porro ut? Exercitationem voluptatem sint consectetur cupiditate itaque recusandae ex suscipit dolorum cum, maxime veritatis dolore libero corporis?
    Cum inventore incidunt, rem placeat nemo alias corporis aspernatur quam neque? Asperiores necessitatibus nobis corrupti sit velit, nesciunt officiis. In harum ea, labore fugiat architecto velit autem excepturi officia ipsum?
    Magnam praesentium ipsa eius veniam quia sed. Ipsam aliquid recusandae nulla. Aut tempora doloremque consectetur cumque, nam aliquid, modi officiis dicta quod suscipit nulla nostrum corrupti at deleniti quia impedit.
    Molestiae assumenda atque quibusdam recusandae non nobis incidunt dignissimos earum! Facilis voluptatum, dolores consequatur quam possimus ducimus. Accusantium, voluptatum eligendi minima quibusdam culpa aperiam, eius, consectetur qui ea explicabo facilis!
    Inventore labore odio, possimus perspiciatis placeat ipsum saepe! Molestiae velit minima sunt architecto natus doloremque magnam explicabo omnis, rem non eum deleniti suscipit itaque? Minima perspiciatis quis nemo officiis tempora!
    Distinctio nihil, alias laudantium at dolore quidem, aliquam, qui nostrum dicta asperiores fugiat tempora! Maiores, sed et obcaecati nulla culpa repellendus possimus fugiat illum suscipit magnam provident facilis dolor architecto?
</div>

<?php
    include "../part/foot.php"
?>


